version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@dev:alpha

workflows:
  deploy:
    jobs:
      - approval-for-deploy-tested-up-to-bump:
          type: approval
      - wp-svn/deploy-tested-up-to-bump:
          dry-run: squirrel
          requires:
            - approval-for-deploy-tested-up-to-bump
