version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@dev:10ee98d2da1b298d67e8572b829e6ee3c9375ebc

workflows:
  deploy:
    jobs:
      - approval-for-deploy-tested-up-to-bump:
          type: approval
      - wp-svn/deploy-tested-up-to-bump:
          dry-run: true
          requires:
            - approval-for-deploy-tested-up-to-bump
