version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@dev:alpha

workflows:
  deploy:
    jobs:
      - wp-svn/deploy:
          dry-run: true
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: kienstra-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
